name: "\U0001F680 Propose a new  rule"
description: 'Propose a new rule to be added to the plugin'
title: 'New Rule: (fill in)'
labels:
  - rule
  - feature
body:
  - type: markdown
    attributes:
      value: By opening an issue, you agree to abide by the [Open JS Foundation Code of Conduct](https://eslint.org/conduct).
  - type: input
    attributes:
      label: Rule details
      description: What should the new rule do?
    validations:
      required: true
  - type: input
    attributes:
      label: Related CVE
      description: We only accept new rules that have a published [CVE](https://www.redhat.com/en/topics/security/what-is-cve).
    validations:
      required: true
  - type: textarea
    attributes:
      label: Example code
      description: Please provide some example JavaScript code that this rule will warn about. This field will render as JavaScript.
      render: js
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Participation
      options:
        - label: I am willing to submit a pull request to implement this rule.
          required: false
  - type: textarea
    attributes:
      label: Additional comments
      description: Is there anything else that's important for the team to know?
