name: Pull Request Titles
on: pull_request

jobs:
  conventional:
    name: Conventional PR
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@v4
      - uses: beemojs/conventional-pr-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-preset: conventional-changelog-conventionalcommits
